### ISSUE TITLE
自定义设置的返回类型,能自动驼峰转换吗

### ISSUE THREAD

**Issue by masankin** [blinkfox/fenix#10]
自定义设置的返回类型,能自动驼峰转换吗
字段 user_id 值自动映射至变量 userId

**Comment by blinkfox** [comment]
暂不支持，自定义转换 Bean ，本质上用的也是 `Hibernate` 中的方法，不能自己控制。

**Comment by masankin** [comment]
> 暂不支持，自定义转换 Bean ，本质上用的也是 `Hibernate` 中的方法，不能自己控制。

那能从 implements ResultTransformer 入手吗

**Comment by blinkfox** [comment]
@masankin 你可以看看源码中 `FenixResultTransformer` 类的 `transformTuple` 方法，应该可以做到，你先试试，后续我有时间，也看看

**Comment by masankin** [comment]
@blinkfox 好的

**Comment by blinkfox** [comment]
最近研究了下，不行，如果不使用 `as` 设置别名，根不拿不到那个原本的字段名称，也就没法去作转换了。
