### ISSUE TITLE
希望demo里面有多表关联的JPQL示例

### ISSUE THREAD

**Issue by liushaoCode** [blinkfox/fenix#13]
因为最好是面向对象编程
所以想要的例子最好如下

对象A.leftjoin对象B 这种

**Comment by blinkfox** [comment]
其实就是 JPQL 语句或原生 SQL 语句，以后有时间可以增加一些吧

**Comment by liushaoCode** [comment]
恩 底层肯定是一样的 所以就需要你们大佬做封装嘛  封装的能力和代码的美感暂时我还不行。。。
所以说现在目前这个框架还不支持对象A.left join.对象B 这种吗

**Comment by blinkfox** [comment]
支持，你自己可以试试，代码[单元测试](https://github.com/blinkfox/fenix/blob/develop/src/test/resources/fenix/BlogRepository.xml)里面也有表连接的示例，只不过我写的直接内连接，你换成 left join 一样。

**Comment by liushaoCode** [comment]
恩 好的 感谢 要是能优化成完全去xml化就好了
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"闪烁之狐 (blinkfox)"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年4月20日(星期一) 下午3:53
 收件人:&nbsp;"blinkfox/fenix"<fenix@noreply.github.com&gt;;
 抄送:&nbsp;"just_do_it"<1028928768@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [blinkfox/fenix] 希望demo里面有多表关联的JPQL示例 (#13)

 

 

 
支持，你自己可以试试，代码单元测试里面也有表连接的示例，只不过我写的直接内连接，你换成 left join 一样。

**Comment by blinkfox** [comment]
@liushaoCode 你是说 Java 的写法吗？也支持 `left join` 啊，两者只是写法形式不一样而已。源代码在[这里](https://github.com/blinkfox/fenix/blob/develop/src/main/java/com/blinkfox/fenix/core/Fenix.java#L329)。

**Comment by blinkfox** [comment]
这个先关闭了哈
