### ISSUE TITLE
使用语义化标签传递参数问题

### ISSUE THREAD

**Issue by wenhaonan** [blinkfox/fenix#17]
<andLike field="t.DESCRIPTION" value="criteria.description" match="criteria.description != empty" />

此时在 criteria 中如果不传递 description 参数就会报错, 请问如何先判断 criteria 对象中有没有 description 这个属性, 再进行判空呢

**Comment by wenhaonan** [comment]
我使用了 ? 操作符依然会报错
com.blinkfox.fenix.exception.ParseExpressionException: 【Fenix 异常提示】解析表达式异常，解析出错的表达式为:【?criteria.checkType != empty】.

**Comment by blinkfox** [comment]
`criteria`  是个什么样的对象，还有你的代码大概怎么写的呢

**Comment by wenhaonan** [comment]
哇, 你回复的好快! 
criteria是一个Map对象

<andLike field="t.CHECK_TYPE" value="criteria.checkType" match="?criteria.checkType != empty" /> 这是整个条件

然后是反射的结果
method.invoke(bean, params, pageable);

**Comment by wenhaonan** [comment]
我在`match` 条件外边套了一层`()`, 貌似欧克了

**Comment by wenhaonan** [comment]
`<andLike field="t.CHECK_TYPE" value="criteria.checkType" match="(?criteria.?checkType != empty)" />`
这样写好像ok了
