### ISSUE TITLE
关于是否支持增量更新的探讨

### ISSUE THREAD

**Issue by pengten** [blinkfox/fenix#20]
最近在使用fenix过程中，发现增量更新的需求非常普遍。由于JPA的原本的特性并不支持，那么fenix作为扩展库是否可以提供简单通用的API来支持这个功能呢？

**Comment by blinkfox** [comment]
@yy1098029419 你的增量更新是指对某条数据的所有字段，进行增量更新吗，你可以详细说明下。

**Comment by yy1098029419** [comment]
@blinkfox 这里的增量更新指的是只对当前对象的非null字段进行update和insert

**Comment by blinkfox** [comment]
我后续想想怎么做吧，你有好的想法也可以说下或者贡献代码。

**Comment by blinkfox** [comment]
@pengten 字段增量更新的功能在 2.4.0 版本已经实现了，你后续可以参考[这里的文档](https://blinkfox.github.io/fenix/#/cud/not-null-update)使用。
