### ISSUE TITLE
关于@EnableFenix注解配置包路径的问题

### ISSUE THREAD

**Issue by cn-nemo** [blinkfox/fenix#27]
jpa（dao）层的包根路径和@EnableFenix所在启动类包根路径一致时使用正常（即@QueryFenix被识别时候）；
但当根路径不同时候，@EnableFenix无法配置不同的包路径，所以@QueryFenix不能被扫描识别，所以报错说Repository的相关方法提示命名不规范（前提知识，jpa Repository的方法命名，如果使用@Query是可以自由命名的（即自定义sql），但当jpa发现没有自定义sql时候要求方法名符合命名规则，不能自用命名，报错）。
作者是否需增加@EnableFenix配置不同的包路径，像@EnableJpaRepositories(basePackages 。。。。。。

**Comment by yy1098029419** [comment]
@EnableJpaRepositories(repositoryFactoryBeanClass = FenixJpaRepositoryFactoryBean.class, basePackages = "xxxx")
您好，介于您的问题，可以先使用以上方式替换 @EnableFenix 注解。

**Comment by yy1098029419** [comment]
@cn-nemo 
@EnableJpaRepositories(repositoryFactoryBeanClass = FenixJpaRepositoryFactoryBean.class, basePackages = "xxxx")
您好，介于您的问题，可以先使用以上方式替换 @EnableFenix 注解。

**Comment by cn-nemo** [comment]
> @cn-nemo
> @EnableJpaRepositories(repositoryFactoryBeanClass = FenixJpaRepositoryFactoryBean.class, basePackages = "xxxx")
> 您好，介于您的问题，可以先使用以上方式替换 @EnableFenix 注解。

嗯试试看

**Comment by blinkfox** [comment]
原本 Fenix 的使用方式就是 `@EnableJpaRepositories(repositoryFactoryBeanClass = FenixJpaRepositoryFactoryBean.class)`，后续版本，增加了 `@EnableFenix` 注解，这个注解就是引用了 `@EnableJpaRepositories` 这个注解，通常情况下使用这个即可，如果想自定义包路径或者多数据源时使用 JPA 原生的 `@EnableJpaRepositories` 就行。

**Comment by chenmu5241** [comment]
估计你使用的方式跟我类似，是再跟实体类放在了一起了吧，这种问题你排查的时候看target目录里面是不是又xml文件，没有的话就改动maven的pom文件里resource就好了

**Comment by cn-nemo** [comment]
公共框架的dao层独立项目（包根路径可能不同）。这是常见需求。用作者的做法可以。

**Comment by blinkfox** [comment]
新版本已经可以在 `@EnableFenix` 中去使用其他配置参数了。
