### ISSUE TITLE
xml如何热更新

### ISSUE THREAD

**Issue by azu-zhou** [blinkfox/fenix#35]
现在在xml写的hql在修改后，需要重启项目。如何可以热更新呢。

**Comment by azu-zhou** [comment]
我也尝试过手动调用FenixConfigManager.getInstance().initLoad(FenixConfigManager.getInstance().getFenixConfig());
但是xml路径不对，我的xml路径是自定义的，手动调用的时候路径取的是默认路径，并不是我自定义路径

**Comment by blinkfox** [comment]
最早 1.0.0 的时候有，但是后来版本去掉了，因为一般部署后 IDE 不去热更新 `xml` 文件的内容，所以，也就没法热加载新的内容到内存中，现在新版 IDEA 应该 可以了，后续版本可以考虑再加回来。

你的这种方式也是可以的，你自定义了 xml 路径的话，你需要调用对应的 FenixConfig 中的 `setXmlLocations()` 方法那么参数也得改改，还有其他很多参数可以配置，使用方式可以参考[这个文档](https://blinkfox.github.io/fenix/#/quick-install?id=%f0%9f%9a%a3-4-%e5%8a%a0%e8%bd%bd-fenix-%e9%85%8d%e7%bd%ae%e4%bf%a1%e6%81%af)里面的加载方式。

**Comment by blinkfox** [comment]
@azu-zhou 新的 `v2.4.1` 版本新增了 [debug 模式](https://blinkfox.github.io/fenix/#/more/debug-mode) 的功能，你可以升级下。
