### ISSUE TITLE
 Could you improve this extended xml tag prompt function

### ISSUE THREAD

**Issue by fangshixian** [blinkfox/fenix#36]
I want to use it in my project, but this tag does not have any hints, and it is not smooth to write. So if the xml hint and other peripheral functions can be more perfect, it would be better

**Comment by pengten** [comment]
that sounds good!

**Comment by blinkfox** [comment]
要做这个功能，可能就需要做 `Intellij IDEA` 或者其他开发工具的插件才行了，后续有时间的话可以做一下。

**Comment by pengten** [comment]
我正在尝试通过定义 Fenix 的 XSD 文件来实现。

**Comment by pengten** [comment]
@blinkfox 我尝试定义了 xsd，能满足 xml 元素的自动补全，但是需要在 xml 进行一些定义：
![image](https://user-images.githubusercontent.com/30648785/106116183-94851f00-618c-11eb-8612-cc3f210836ce.png)
如果该方案能够接受，我们还需要一个地址用来下载 xsd 文件

**Comment by blinkfox** [comment]
可以，不过这种方案能支持自定义的标签吗？

**Comment by pengten** [comment]
自定义标签允许存在，但是不会自动补全。

**Comment by blinkfox** [comment]
嗯，那可以

**Comment by blinkfox** [comment]
@pengten 最近做了下这个，发现 `dom4j` 去解析有命名空间的 xml 时，会有问题，要改写法了，改动比较多，目前决定先不在最近的一些版本中做这个功能了

**Comment by pengten** [comment]
@blinkfox get!

**Comment by xzxzhixin** [comment]
能不能添加一个标签，支持不同数据库写原生sql

**Comment by blinkfox** [comment]
将关闭此 issue。
