### ISSUE TITLE
判断不同的数据库

### ISSUE THREAD

**Issue by xzxzhixin** [blinkfox/fenix#41]
mybatis中有<if test="_databaseId == 'MySQL' or _databaseId == 'Microsoft SQL Server'">判断不同数据库加载不同的SQL，希望作者可以考虑这个功能，这样可以有更好的通用性

**Comment by blinkfox** [comment]
@xzxzhixin JPA 中建议写 JPQL 语句，本身就是可以跨数据库的。
在 Fenix 中你可以自定义标签，先写一下这个功能，如果觉得这个功能确实很必要且成熟了的话，你可以提 `Pull Request` 请求，我合并内置进去。

**Comment by blinkfox** [comment]
该 issue 长期未回复，我将关闭这个 issue。
