### ISSUE TITLE
能提供idea上用的插件吗

### ISSUE THREAD

**Issue by jgaybjone** [blinkfox/fenix#44]
能提供idea上的插件吗，类似mybatis的，能在xml写sql的时候自动提示，接口repository <=> xml 能相互链接快速跳转和检查。

**Comment by blinkfox** [comment]
目前没有这方面的精力和计划

**Comment by jgaybjone** [comment]
我开发了一个接口和xml跳转的idea 插件 https://plugins.jetbrains.com/plugin/17158-fenix

**Comment by blinkfox** [comment]
@jgaybjone 可以，后续我们试用下，也写到文档里。

**Comment by hexian** [comment]
> 我开发了一个接口和xml跳转的idea 插件 https://plugins.jetbrains.com/plugin/17158-fenix

超赞👍🏻  之前我也在想这个插件得我问题，另外还有一个事情想问下老哥，比如:
xml里面的sql内容是:
        SELECT
            b.id,
            b.userId,
            b.title,
            b.author 
        FROM
            Blog AS b

插件可否提供一个快捷键自动加上别名，借助sqlparse这样成熟的工具，变成下面的sql，会方便一些，感谢！

        SELECT
            b.id AS blogId,
            b.userId AS userId,
            b.title AS title,
            b.author AS author
        FROM
            Blog AS b

**Comment by jgaybjone** [comment]
> 借助sqlparse这样成熟的工具，变成下面的sql，会方便一些，感谢！

兄弟，我不太会，你fork 我的仓库自己试试 看吧

**Comment by hexian** [comment]
好的，后面我抽时间学下idea的psi的用法。------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月16日(星期五) 中午1:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blinkfox/fenix] 能提供idea上用的插件吗 (#44)

**Comment by jgaybjone** [comment]
> > 我开发了一个接口和xml跳转的idea 插件 https://plugins.jetbrains.com/plugin/17158-fenix
> 
> 超赞👍🏻 之前我也在想这个插件的问题，另外还有一个事情想问下老哥，比如:
> xml里面的sql内容是:
> SELECT
> b.id,
> b.userId,
> b.title,
> b.author
> FROM
> Blog AS b
> 
> 插件可否提供一个快捷键自动加上别名，借助sqlparse这样成熟的工具，变成下面的sql，会方便一些，感谢！
> 
> ```
>     SELECT
>         b.id AS blogId,
>         b.userId AS userId,
>         b.title AS title,
>         b.author AS author
>     FROM
>         Blog AS b
> ```

![230156170229145189229144141](https://user-images.githubusercontent.com/42432240/127738943-94aecc4b-e3f8-429d-97dd-983bab1bb24a.gif)
这样可以不

**Comment by hexian** [comment]
₍₍Ϡ(੭•̀ω•́)੭✧⃛ ₍₍Ϡ(੭•̀ω•́)੭✧⃛ ₍₍Ϡ(੭•̀ω•́)੭✧⃛------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年7月31日(星期六) 晚上7:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [blinkfox/fenix] 能提供idea上用的插件吗 (#44)

**Comment by dubai** [comment]
> > > 我开发了一个接口和xml跳转的idea 插件 https://plugins.jetbrains.com/plugin/17158-fenix
> > 
> > 
> > 超赞👍🏻 之前我也在想这个插件的问题，另外还有一个事情想问下老哥，比如:
> > xml里面的sql内容是:
> > SELECT
> > b.id,
> > b.userId,
> > b.title,
> > b.author
> > FROM
> > Blog AS b
> > 插件可否提供一个快捷键自动加上别名，借助sqlparse这样成熟的工具，变成下面的sql，会方便一些，感谢！
> > ```
> >     SELECT
> >         b.id AS blogId,
> >         b.userId AS userId,
> >         b.title AS title,
> >         b.author AS author
> >     FROM
> >         Blog AS b
> > ```
> 
> ![230156170229145189229144141](https://user-images.githubusercontent.com/42432240/127738943-94aecc4b-e3f8-429d-97dd-983bab1bb24a.gif) 这样可以不

为啥下载最新版本不支持呢？

**Comment by blinkfox** [comment]
@jgaybjone 感谢贡献，在新版本里面，把该 IDEA 插件和贡献人员已经写到文档里面了，我也会关闭此 `issue` 。
