### ISSUE TITLE
有没有办法支持动态EntityGraph呢？

### ISSUE THREAD

**Issue by wangguofeng1923** [blinkfox/fenix#50]
类似于：https://github.com/Cosium/spring-data-jpa-entity-graph
当然了如果能把fenix和上面的这个给整合到一起就更完美了

**Comment by blinkfox** [comment]
我不太了解他到底要解决的痛点是什么，看他源码代码量也很少，你可以再评估下是否有必要，真有必要的话，你再看看怎么整合，可以多话提合并请求。
