### ISSUE TITLE
XML文件不支持 <!DOCTYPE fenixs PUBLIC 校验

### ISSUE THREAD

**Issue by jgaybjone** [blinkfox/fenix#53]
自己写了xml提示校验的如图：
![image](https://user-images.githubusercontent.com/42432240/132304295-cc7d09c9-98bf-4acb-93bc-6c87114a1e2c.png)
启动应用时候会报错：
![image](https://user-images.githubusercontent.com/42432240/132304669-d75c4df7-8759-4d29-b2fd-7a25b635f629.png)

**Comment by bearmr** [comment]
这个怎么加哈老哥

**Comment by bearmr** [comment]
有解决吗

**Comment by jgaybjone** [comment]
校验放到一行，编译的时候用maven活着gradle task删除这一行

**Comment by blinkfox** [comment]
不建议加 `<!DOCTYPE fenixs PUBLIC` 相关的内容，我要关闭此 `issue` 了。
