### ISSUE TITLE
sql查询*的时候不会自动大小写转换使用的xml查询

### ISSUE THREAD

**Issue by bearmr** [blinkfox/fenix#57]

**Comment by bearmr** [comment]
返回的vo驼峰的就返回不了数据,就不能使用*

**Comment by blinkfox** [comment]
@bearmr 你的问题，跟这个 [issue(56)](https://github.com/blinkfox/fenix/issues/56) 类似，Fenix 不够“聪明”，不会随意去对字段去进行转换的。

**Comment by blinkfox** [comment]
新版本 `v2.7.0` 已发布，将关闭此 `issue`。

新版本变更记录如下：

- 新增了 ActiveRecord 模式，简单场景的“**增删改查**”或**动态查询**更加方便、优雅；
- 新增了多种可自定义的查询结果列转换为对象实体的转换策略，包括"**基于 as 别名转换**"（默认）、"**下换线转驼峰**"、"**去除前缀的下划线转驼峰**"和"**基于 Column 注解转换**"等；
- 新增了 `@QueryFenix` 注解中的 `resultType` 的结果实体类型属性，跟 XML 中的 `resultType` 同义，后续推荐使用注解标注结果类型，重构代码时，能更好的利用上的 Java 的静态编译检查。
- 新增了 `NanoId` 的主键生成策略和 Java API 调用方式；
- 新增和改进了部分文档中的内容，添加了 `IDEA` 插件地址和其他贡献者的列表；
