### ISSUE TITLE
作者去哪里了,为何不更新了呢?还有很多bug呢

### ISSUE THREAD

**Issue by yuxicun** [blinkfox/fenix#58]
老哥,还有bug呢,可否升级,不能放弃我们呀

**Comment by pengten** [comment]
什么bug？现有的issue吗？

**Comment by blinkfox** [comment]
@yuxicun SpringData JPA 每一版都发布，我都会进行测试的，你 `issue` 中说的问题，是使用上的问题，我们诸多项目中都一直在用的，真有 `bug` 会及时修复的。

**Comment by yuxicun** [comment]
![image](https://user-images.githubusercontent.com/18489852/159210967-142b11f5-4ffe-4037-b7a3-3ce73d123c81.png)
![image](https://user-images.githubusercontent.com/18489852/159210995-73547b78-ce88-46a5-baa2-a55e6b93a949.png)
我改写了此类,使之能支持下划线自助转驼峰

**Comment by yuxicun** [comment]
当使用了resultType时,此类必须指向一个vo类,如果指向了一个实体类,将导致查询结果无法映射到实体字段中

**Comment by blinkfox** [comment]
新版本开启了，我周末晚上抽空开发此功能，会默认附带一些常用的 Bean 转换器，尝试利用上 `@Column` 注解，也允许在 `@QueryFenix` 注解中自定义自己的 Bean 转换器。

**Comment by blinkfox** [comment]
新版本 `v2.7.0` 已发布，将关闭此 `issue`。

新版本变更记录如下：

- 新增了 ActiveRecord 模式，简单场景的“**增删改查**”或**动态查询**更加方便、优雅；
- 新增了多种可自定义的查询结果列转换为对象实体的转换策略，包括"**基于 as 别名转换**"（默认）、"**下换线转驼峰**"、"**去除前缀的下划线转驼峰**"和"**基于 Column 注解转换**"等；
- 新增了 `@QueryFenix` 注解中的 `resultType` 的结果实体类型属性，跟 XML 中的 `resultType` 同义，后续推荐使用注解标注结果类型，重构代码时，能更好的利用上的 Java 的静态编译检查。
- 新增了 `NanoId` 的主键生成策略和 Java API 调用方式；
- 新增和改进了部分文档中的内容，添加了 `IDEA` 插件地址和其他贡献者的列表；
