### ISSUE TITLE
Jakarta EE apis 导致的 java.lang.NoClassDefFoundError: javax/persistence/EntityManager

### ISSUE THREAD

**Issue by imhansai** [blinkfox/fenix#74]
由于 [Spring Boot 3.0 has migrated from Java EE to Jakarta EE APIs for all dependencies. ](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Release-Notes)

导入的一些类需要从 javax.persistence.x 迁移到 jakarta.persistence.x

感觉是不是需要分两个版本维护呢？毕竟不兼容

**Comment by imhansai** [comment]
提了个 #75 ,仅仅简单处理了 jakarta 包。不过我看历史 issues 中可能会做国际化等等，而且由于 hibernate 6 搞了 sqm 等等，不知道会不会有重大影响

**Comment by blinkfox** [comment]
@imhansai 谢谢贡献，我后续有时间看看，我看改动挺多的，怕有啥大的影响

**Comment by imhansai** [comment]
> 

好的:)

**Comment by murainwood** [comment]
我folk了一个版本，到spring6和hibernate6. 目前看来，也就xml hql/sql 可以相对容易升级。
springboot3，想完全兼容，工作量太大太大太大了
