### ISSUE TITLE
如何实现热部署呢,就是在调试模式下,我修改了xml文件,发现没有办法热生效,需要重启,有点麻烦

### ISSUE THREAD

**Issue by yuxicun** [blinkfox/fenix#8]
如何实现热部署呢,就是在调试模式下,我修改了xml文件,发现没有办法热生效,需要重启,有点麻烦

**Comment by blinkfox** [comment]
早先第一版的时候倒是有，后续版本去掉了这个功能，有些鸡肋，以前我使用的热加载插件，不会加载最新的 XML 文件，只是加载了最新的 Java 代码，感觉没啥用，就去掉了。

**Comment by yuxicun** [comment]
好的,谢谢

**Comment by blinkfox** [comment]
@yuxicun 新的 `v2.4.1` 版本新增了 [debug 模式](https://blinkfox.github.io/fenix/#/more/debug-mode)的功能，你可以升级下。
